version: 0.2

env:
  parameter-store:
    aws_access_key_id: "/CodeBuild/packer/AWS_ACCESS_KEY_ID"
    aws_secret_access_key: "/CodeBuild/packer/AWS_SECRET_ACCESS_KEY" 

phases:
  pre_build:
    commands:
      - cd terraform
      - terraform init -no-color
      - terraform refresh -no-color
      - terraform apply -auto-approve -no-color  
      - "terraform output -json | jq '{ subnet_id: .subnet_id.value, vpc_id: .vpc_id.value }' > ../terraform.json"
      - cd ..
  build:
    commands:
      - packer build -var-file=terraform.json -color=false -var "aws_access_key_id=$aws_access_key_id" -var "aws_secret_access_key=$aws_secret_access_key" ecs_ami.json
  post_build:
    commands:
      - cd terraform
      - terraform destroy -force -no-color 
      - cd ..
artifacts:
   files:
     - manifest.json
   discard-paths: yes       
      