version: 0.2

phases:
  install:
    commands:
      - sudo pip install boto3
      - wget https://releases.hashicorp.com/terraform/0.11.6/terraform_0.11.6_linux_amd64.zip
      - rm terraform -rf
      - unzip terraform_0.11.6_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_0.11.6_linux_amd64.zip
      - apt-get update
      - apt-cache search source
      - apt-get install -y curl jq
      - echo "Installing HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
  build:
    commands:
      - ./ci/build.sh
