version: 0.2

env:
  parameter-store:
    aws_access_key_id: "/CodeBuild/packer/AWS_ACCESS_KEY_ID"
    aws_secret_access_key: "/CodeBuild/packer/AWS_SECRET_ACCESS_KEY" 

phases:
  pre_build:
    commands:
      - cd terraform
      - terraform init -no-color
      - terraform refresh -no-color
      - terraform apply -auto-approve -no-color  
      - "terraform output -json | jq '{ subnet_id: .subnet_id.value, vpc_id: .vpc_id.value }' > ../terraform.json"
      - cd ..
      - echo $aws_access_key_id
  build:
    commands:
      - curl https://releases.hashicorp.com/consul/1.2.2/consul_1.2.2_linux_amd64.zip -o files/bin/consul.zip
      - unzip -d files/bin files/bin/consul.zip
      - rm files/bin/consul.zip
      -
      - curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.5/goss-linux-amd64 -o files/bin/goss
      -
      - curl -L https://github.com/cortesi/modd/releases/download/v0.5/modd-0.5-linux64.tgz -o files/bin/modd.tgz
      - tar -xvzf files/bin/modd.tgz -C files/bin
      - mv files/bin/modd-0.5-linux64/modd files/bin/modd
      - rm files/bin/modd.tgz
      - rmdir files/bin/modd-0.5-linux64 
      -
      - curl -L https://github.com/google/cadvisor/releases/download/untagged-ea64a390962dd82b3913/cadvisor -o files/bin/cadvisor
      - 
      - curl -L https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz -o files/bin/node_exporter.tar.gz
      - tar -xvzf files/bin/node_exporter.tar.gz -C files/bin
      - mv files/bin/node_exporter-0.16.0.linux-amd64/node_exporter files/bin/node_exporter
      - rm files/bin/node_exporter.tar.gz
      - rm -rf files/bin/node_exporter-0.16.0.linux-amd64
       
      - packer build -var-file=terraform.json -color=false -var "aws_access_key_id=$aws_access_key_id" -var "aws_secret_access_key=$aws_secret_access_key" ecs_ami.json
  post_build:
    commands:
      - cd terraform
      - terraform destroy -force -no-color 
      - cd ..
      - AMI=`jq '.builds[0].artifact_id | split(":")[1]' -r manifest.json`
      - echo ecs_ami_id = \"$AMI\" > packer.auto.tfvars
artifacts:
   files:
     - manifest.json
     - packer.auto.tfvars
   discard-paths: yes       
      