output.logstash:
  hosts: ["logstash.service.consul:5044"]
  backoff.max: 6000s
  
filebeat.config.inputs:
  enabled: true
  path: /etc/filebeat/containers/*.yml
  reload.enabled: true
  reload.period: 3s
