file:
  /opt/consul/conf/monitoring_consul.json:
    exists: true
    mode: "0644"
    size: 440
    owner: root
    group: root
    filetype: file
    contains: []
  /opt/mount1/grafana:
    exists: true
    mode: "0755"
    size: 4096
    filetype: directory
    contains: []
  /opt/mount1/grafana_logs:
    exists: true
    mode: "0755"
    size: 4096
    filetype: directory
    contains: []
  /opt/mount1/grafana_plugins:
    exists: true
    mode: "0755"
    size: 4096
    owner: root
    group: root
    filetype: directory
    contains: []
  /opt/mount1/graphite:
    exists: true
    mode: "0755"
    size: 4096
    owner: root
    group: root
    filetype: directory
    contains: []
  /opt/mount1/graphite_logrotate_config:
    exists: true
    mode: "0755"
    size: 4096
    owner: root
    group: root
    filetype: directory
    contains: []
package:
  file:
    installed: true
    versions:
    - "5.30"
port:
  tcp:22:
    listening: true
    ip:
    - 0.0.0.0
  tcp6:22:
    listening: true
    ip:
    - '::'
service:
  sshd:
    enabled: true
    running: true
group:
  sshd:
    exists: true
    gid: 74
process:
  sshd:
    running: true
