package:
  file:
    installed: true
    versions:
    - "5.30"
port:
  tcp:22:
    listening: true
    ip:
    - 0.0.0.0
  tcp6:22:
    listening: true
    ip:
    - '::'
service:
  sshd:
    enabled: true
    running: true
group:
  sshd:
    exists: true
    gid: 74
process:
  sshd:
    running: true
