package:
  file:
    installed: true
    versions:
    - "5.30"
port:
  tcp:22:
    listening: true
    ip:
    - 0.0.0.0
  tcp6:22:
    listening: true
    ip:
    - '::'
file:
  /usr/local/bin/consul:
    exists: true
    mode: "0755"
    owner: root
    group: root
    filetype: file
  /usr/local/bin/goss:
    exists: true
    mode: "0755"
    owner: root
    group: root
    filetype: file
  /usr/local/bin/modd:
    exists: true
    mode: "0755"
    owner: root
    group: root 
    filetype: file
  /usr/local/bin/cadvisor:
    exists: true
    mode: "0755"
    owner: root
    group: root
    filetype: file  
  /etc/modd/modd.conf:
    exists: true
    mode: "0664"
    owner: root
    group: root
    filetype: file  
  /etc/init.d/modd:
    exists: true
    mode: "0775"
    owner: root
    group: root
    filetype: file
service:
  sshd:
    enabled: true
    running: true
  goss:
    enabled: true
    running: true
  modd:
    enabled: true
    running: true
  cadvisor:
    enabled: true
    running: true
group:
  sshd:
    exists: true
    gid: 74
process:
  sshd:
    running: true
  consul:
    running: true
  goss:
    running: true
  modd:
    running: true
  cadvisor:
    running: true
  dockerd:
    running: true
  crond:
    running: true
http:
  http://localhost:8090/metrics:
    status: 200
    timeout: 1000
    allow-insecure: false
