package:
  file:
    installed: true
    versions:
    - "5.30"
port:
  tcp:22:
    listening: true
    ip:
    - 0.0.0.0
  tcp6:22:
    listening: true
    ip:
    - '::'
service:
  sshd:
    enabled: true
    running: true
  goss:
    enabled: true
    running: true
  modd:
    enabled: true
    running: true
  consul:
    enabled: true
    running: true
  cadvisor:
    enabled: true
    running: true
group:
  sshd:
    exists: true
    gid: 74
process:
  sshd:
    running: true
http:
  http://localhost:8080/metrics:
    status: 200
    timeout: 1000
    allow-insecure: false
