#!/bin/bash
#
# 
#
# chkconfig: 2345 14 86
#
# processname: modd
# pidfile: /var/run/modd.pid

RUNAS=root

PIDFILE=/var/run/modd.pid
LOGFILE=/var/log/modd.log
CONFIGFILE=/etc/modd/modd.conf
EXECFILE=/usr/local/bin/modd

start() {
    if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
        echo 'Service already running' >&2
        return 1
    fi
    echo 'Starting service…' >&2
    local CMD="$EXECFILE -f $CONFIGFILE &> \"$LOGFILE\" & echo \$!"
    echo $CMD
    su -c "$CMD" $RUNAS > "$PIDFILE"
    echo 'Service started' >&2
}

stop() {
    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
        echo 'Service not running' >&2
        return 1
    fi
    echo 'Stopping service…' >&2
    kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
    echo 'Service stopped' >&2
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|status|reload}"
        exit 1
        ;;
esac
exit $?